In [1]:
!pip install scikit-learn

In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split

### DATA

In [4]:
#Create a sample X,y data
X,y = np.arange(10).reshape((5,2)), range(5)

In [5]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
list(y)

[0, 1, 2, 3, 4]

### Split the data into Train and Test 

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [8]:
X_train

array([[4, 5],
       [0, 1],
       [2, 3]])

In [9]:
y_train

[2, 0, 1]

In [10]:
X_test

array([[8, 9],
       [6, 7]])

In [11]:
y_test

[4, 3]

### Model

In [12]:

model = LinearRegression(normalize=True)


In [13]:
model.fit(X_train, y_train)

LinearRegression(normalize=True)

In [14]:
predictions = model.predict(X_test)

In [15]:
predictions

array([4., 3.])

### Analyse your Model 

In [16]:
# print the coefficients
print(model.intercept_)
print(model.coef_)

-0.24999999999999978
[0.25 0.25]


In [17]:
model.score(X_train,y_train)

1.0

In [18]:
from sklearn import metrics

In [19]:
# calculate MAE, MSE, RMSE
print(metrics.mean_absolute_error(y_test, predictions))
print(metrics.mean_squared_error(y_test, predictions))
print(np.sqrt(metrics.mean_squared_error(y_test, predictions)))

8.881784197001252e-16
7.888609052210118e-31
8.881784197001252e-16
