## NumPy Arrays

In [1]:
my_list = [1,2,3]
my_list


[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr  = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6]]
my_mat

[[1, 2, 3], [4, 5, 6]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.15331839, 0.48589979, 0.76257878, 0.58188424, 0.74689136])

In [15]:
np.random.rand(5,5)

array([[0.24800779, 0.66484927, 0.60947298, 0.50774884, 0.82034878],
       [0.86190281, 0.20311555, 0.8149512 , 0.1860871 , 0.89271364],
       [0.31170915, 0.96457755, 0.75809271, 0.44781354, 0.4303042 ],
       [0.09525343, 0.96232447, 0.66139419, 0.06282486, 0.57051651],
       [0.31791806, 0.72980865, 0.23992959, 0.03198417, 0.8963528 ]])

In [16]:
# standard normal distribution
np.random.randn(5)

array([-1.30046338,  1.18838189,  0.52542801,  1.73140185, -0.42575206])

In [17]:
np.random.randn(5,5)

array([[ 0.10509833,  2.31433001, -1.47032185,  0.45449268,  1.51701938],
       [-1.12469939, -0.37570966, -0.29014325,  0.24922823, -0.80366757],
       [ 0.58649197, -0.3941257 ,  1.00285183, -0.8429681 , -0.78960977],
       [ 1.02935976,  0.71862133,  0.0441327 , -1.63410617, -1.73571855],
       [ 0.8089928 ,  0.25394661, -1.69395979, -0.40230815, -0.50862529]])

In [18]:
np.random.randint(1,100)

73

In [19]:
np.random.randint(1,100,10)

array([ 2, 40, 47, 53, 95, 62, 65,  4,  5,  5])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)

In [23]:
ranarr


array([46, 36, 46, 29, 18, 41, 25, 39, 42, 41])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [ ]:
ranarr.max()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmax() # index location of max value

In [ ]:
ranarr.argmin() # index location of min value

In [26]:
arr.shape

(25,)

In [27]:
ranarr.shape

(10,)

In [28]:
new_arr= arr.reshape(5,5)

In [29]:
new_arr.shape

(5, 5)

In [30]:
random_arr = np.random.randint(0,40,50)

In [31]:
random_arr

array([ 8, 30, 13,  4, 17, 25, 33, 32,  6,  7, 23,  3,  1,  7, 21, 13, 37,
       35, 11, 16, 23, 34, 37, 15,  9, 10,  7,  0, 14, 20, 34, 24, 13, 13,
        6,  1,  2, 15, 27, 31,  0, 36, 26, 29, 13,  8, 12, 33, 27,  1])

## Numpy Indexing and Selection

In [33]:
newarr = np.arange(0,11)

In [34]:
newarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
newarr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
newarr[:5:2]

array([0, 2, 4])

In [37]:
newarr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr = newarr[6:]

In [41]:
slice_of_arr 

array([ 6,  7,  8,  9, 10])

### slice_of_array creates only a view of original newarr

In [42]:
slice_of_arr[:]=99

In [43]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [44]:
## notice how all elements from 5th index changed to 99 ?
newarr

array([ 0,  1,  2,  3,  4,  5, 99, 99, 99, 99, 99])

### So if you want to copy an array ?

In [45]:
arr_cpy = newarr[6:].copy()

In [46]:
arr_cpy

array([99, 99, 99, 99, 99])

In [47]:
arr_cpy[:] = 101

In [48]:
arr_cpy

array([101, 101, 101, 101, 101])

In [49]:
newarr

array([ 0,  1,  2,  3,  4,  5, 99, 99, 99, 99, 99])

## MATRIX

In [54]:
arr_2d = np.random.randint(0,5,25)

In [55]:
arr_2d

array([3, 4, 0, 2, 3, 2, 2, 3, 2, 0, 3, 4, 0, 0, 3, 1, 2, 4, 0, 2, 1, 0,
       2, 3, 3])

In [56]:
arr_2d = arr_2d.reshape(5,5)

In [57]:
arr_2d

array([[3, 4, 0, 2, 3],
       [2, 2, 3, 2, 0],
       [3, 4, 0, 0, 3],
       [1, 2, 4, 0, 2],
       [1, 0, 2, 3, 3]])

In [58]:
arr_2d[1,2]

3

In [ ]:
##Slicing in 2D array

In [59]:
arr_2d[:2,1:]

array([[4, 0, 2, 3],
       [2, 3, 2, 0]])

In [61]:
arr_2d[2:,2:]

array([[0, 0, 3],
       [4, 0, 2],
       [2, 3, 3]])

In [ ]:
#conditional slicing 

In [63]:
arr = np.arange(0,11)

In [64]:
bool_arr = arr > 5

In [65]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [67]:
arr[bool_arr] # only returns indexes where bool is true 

array([ 6,  7,  8,  9, 10])

In [68]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr<3]

array([0, 1, 2])

In [70]:
arr_rand_2d = np.arange(50).reshape(5,10)

In [71]:
arr_rand_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
#grab 2,3 to 4,6

arr_rand_2d[2:6,2:6]


array([[22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

## Numpy Operations

In [76]:
arr_op = np.arange(0,11)

In [77]:
arr_op

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr_op * arr_op # scalar multiplication

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [79]:
arr_op + arr_op

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr_op - arr_op

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
arr_op * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
## 

In [84]:
1/0

ZeroDivisionError: division by zero

In [85]:
arr_op / arr_op  # numpy just issues a warning for 0/0, something to be careful about 

<ipython-input-85-6bcc9ffefc07>:1: RuntimeWarning: invalid value encountered in true_divide
  arr_op / arr_op


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
arr_op ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [87]:
np.sqrt(arr_op)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [88]:
np.max(arr_op)

10

In [89]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [90]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [91]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])